kind: Deployment
apiVersion: apps/v1
metadata:
   name: devops
spec:
   replicas: 2
   selector:      
    matchLabels:
     app: devops
   template:
      metadata:
        labels:
          app: devops
      spec:
       containers:
        - name: devops
          image: kaivalyanaik/kube-pipeline
          imagePullPolicy: Always
          ports:
          - containerPort: 80