apiVersion: apps/v1
kind: Deployment
metadata: 
  name: devops-poc
spec:
  replicas: 2
  selector:
    matchLabels: 
      app: devops-poc
  template:
    metadata: 
      labels:
        app: devops-poc
    spec: 
      containers: 
      - name: devops-poc
        image: kaivalyanaik/kube-pipeline
        imagePullPolicy: Always
        ports:
          -containerPort: 80
