apiVersion: apps/v1
kind: Service
metadata:
  name: devops-poc
  labels:
    app: devops-poc
spec:
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 31200
  selector: 
    app: devops
  type: LoadBalancer